//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerberus.Models.edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CerberusDBEntities : DbContext
    {
        public CerberusDBEntities()
            : base("name=CerberusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<FactorySite> FactorySites { get; set; }
        public virtual DbSet<FactorySiteWareHouseClaim> FactorySiteWareHouseClaims { get; set; }
        public virtual DbSet<GroupDepartmentClaim> GroupDepartmentClaims { get; set; }
        public virtual DbSet<GroupFactorySiteClaim> GroupFactorySiteClaims { get; set; }
        public virtual DbSet<GroupWareHouseClaim> GroupWareHouseClaims { get; set; }
        public virtual DbSet<ItemsRegistry> ItemsRegistries { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Warehouse> WareHouses { get; set; }
        public virtual DbSet<ProductionRegistry> ProductionRegistries { get; set; }
    }
}
