//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerberus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupFactorySiteClaim
    {
        public int? id { get; set; }
        public string role_id { get; set; }
        public Nullable<int> factorysite_id { get; set; }
    
        public virtual FactorySite FactorySite { get; set; }
    }
}
