//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cerberus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionRegistry
    {
        public int? Id { get; set; }
        public int production_id { get; set; }
        public int requirement_id { get; set; }
    
        public virtual ItemsRegistry ItemsRegistry { get; set; }
        public virtual ItemsRegistry ItemsRegistry1 { get; set; }
    }
}
